"""Price

Revision ID: 6b34b5b20bc6
Revises: 81573e47e9f8
Create Date: 2024-08-31 15:59:00.571756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b34b5b20bc6'
down_revision: Union[str, None] = '81573e47e9f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('industry', sa.Column('price', sa.Integer(), nullable=False, comment='Price per ton'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('industry', 'price')
    # ### end Alembic commands ###
